"""Shared configuration for the GestureSlides app."""

# --- Camera ---
CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
TARGET_FPS = 30
CAMERA_PROBE_WARMUP_FRAMES = 5
CAMERA_READ_RETRY_SEC = 0.05

# --- MediaPipe ---
MAX_HANDS = 1
MIN_DETECTION_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.4

# --- Gesture: Swipe ---
SWIPE_BUFFER_SIZE = 8
SWIPE_THRESHOLD = 0.04
SWIPE_WINDOW_SEC = 0.45
SWIPE_MIN_SAMPLES = 4

# --- Gesture: Tracking ---
FIST_FRAMES_REQUIRED = 3
NO_HAND_RESET_FRAMES = 3

# --- Cooldown ---
GESTURE_COOLDOWN_SEC = 0.9
IDLE_SLEEP_SEC = 0.05
APP_POLL_INTERVAL_SEC = 0.5

# --- Keyboard keys ---
KEY_NEXT_SLIDE = 'right'
KEY_PREV_SLIDE = 'left'
KEY_PAUSE = 'b'

# --- Visualization ---
VISUALIZATION_WINDOW_NAME = "GestureSlides Visualization"
VISUALIZATION_TEXT_COLOR = (240, 240, 240)
VISUALIZATION_ACCENT_NEXT = (34, 197, 94)
VISUALIZATION_ACCENT_PREV = (59, 130, 246)
VISUALIZATION_ACCENT_ACTION = (239, 68, 68)
VISUALIZATION_ACCENT_TRACK = (245, 158, 11)

# --- Tray ---
ICON_SIZE = 64
TRAY_ICON_MARGIN = 8
ICON_COLOR_ACTIVE = (34, 197, 94)
ICON_COLOR_PAUSED = (107, 114, 128)
ICON_COLOR_BG = (0, 0, 0, 0)
APP_NAME = "GestureSlides"
